//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.269
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Send from Workspace과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AdbFileWindow_Batch_Button {
            get {
                return ResourceManager.GetString("AdbFileWindow_Batch_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send all files from Workspace directory.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AdbFileWindow_Batch_Desc {
            get {
                return ResourceManager.GetString("AdbFileWindow_Batch_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send to Phone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AdbFileWindow_Button {
            get {
                return ResourceManager.GetString("AdbFileWindow_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send modded files 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AdbFileWindow_Desc {
            get {
                return ResourceManager.GetString("AdbFileWindow_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All files checked.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string All_Files_Checked {
            get {
                return ResourceManager.GetString("All_Files_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Autopilot Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Autopilot {
            get {
                return ResourceManager.GetString("Autopilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply muliple mods automatically.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Autopilot_Desc {
            get {
                return ResourceManager.GetString("Autopilot_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exclude mods과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Autopilot_Exclude {
            get {
                return ResourceManager.GetString("Autopilot_Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Autopilot mode is finished.
        ///
        ///Applied mods:
        ///{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Autopilot_Finished {
            get {
                return ResourceManager.GetString("Autopilot_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Include mods과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Autopilot_Include {
            get {
                return ResourceManager.GetString("Autopilot_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If there&apos;s problem, autopiot mode will be paused.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Autopilot_Info {
            get {
                return ResourceManager.GetString("Autopilot_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back to main screen to start autopilot mode.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Autopilot_Start {
            get {
                return ResourceManager.GetString("Autopilot_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t find string with pattern: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cant_Find_String_With_Pattern {
            get {
                return ResourceManager.GetString("Cant_Find_String_With_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Check_Files {
            get {
                return ResourceManager.GetString("Check_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copying Signature... :{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Copying_Signature {
            get {
                return ResourceManager.GetString("Copying_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COPY: File not exists: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Debug_COPY {
            get {
                return ResourceManager.GetString("Debug_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COPYSIGN: File not exists. failed to build?: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Debug_COPYSIGN {
            get {
                return ResourceManager.GetString("Debug_COPYSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OPEN: File not exists: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Debug_OPEN {
            get {
                return ResourceManager.GetString("Debug_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RUN: File not exists.: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Debug_RUN {
            get {
                return ResourceManager.GetString("Debug_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SIGN: File not exists. failed to build?: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Debug_SIGN {
            get {
                return ResourceManager.GetString("Debug_SIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZIP_ADDDIRECTORY: Directory not exists: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Debug_ZIP_ADDDIRECTORY {
            get {
                return ResourceManager.GetString("Debug_ZIP_ADDDIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZIP_ADDFILE: File not exists: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Debug_ZIP_ADDFILE {
            get {
                return ResourceManager.GetString("Debug_ZIP_ADDFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZIP_EXTRACT: No zip file opened.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Debug_ZIP_EXTRACT {
            get {
                return ResourceManager.GetString("Debug_ZIP_EXTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZIP_OPEN: File not exists: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Debug_ZIP_OPEN {
            get {
                return ResourceManager.GetString("Debug_ZIP_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZIP_UPDATE: File not exists: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Debug_ZIP_UPDATE {
            get {
                return ResourceManager.GetString("Debug_ZIP_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deselect all과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Deselect_All {
            get {
                return ResourceManager.GetString("Deselect_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device connected.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Device_Connected {
            get {
                return ResourceManager.GetString("Device_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error caused!:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_Caused {
            get {
                return ResourceManager.GetString("Error_Caused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpacking file... :{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File_Extracting {
            get {
                return ResourceManager.GetString("File_Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File is already patched: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File_Is_Already_Patched {
            get {
                return ResourceManager.GetString("File_Is_Already_Patched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Manager과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File_Manager {
            get {
                return ResourceManager.GetString("File_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Caution: If check files that already exists, it will overwrite.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File_Manager_Caution {
            get {
                return ResourceManager.GetString("File_Manager_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File not exists: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File_Not_Found {
            get {
                return ResourceManager.GetString("File_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No file generated: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File_Output_Not_Found {
            get {
                return ResourceManager.GetString("File_Output_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Packing file... :{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File_Packing {
            get {
                return ResourceManager.GetString("File_Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pull files from phone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Get_Files_From_Phone {
            get {
                return ResourceManager.GetString("Get_Files_From_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Homepage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Included file(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Included_Files {
            get {
                return ResourceManager.GetString("Included_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installing Dummy frameworks.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InstallingDummyFramework {
            get {
                return ResourceManager.GetString("InstallingDummyFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installing framework...: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InstallingFramework {
            get {
                return ResourceManager.GetString("InstallingFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot found {0} file(s).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Missing_Files {
            get {
                return ResourceManager.GetString("Missing_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Java Runtime is missing.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Missing_Java_Runtime {
            get {
                return ResourceManager.GetString("Missing_Java_Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modding Finished.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Modding_Finished {
            get {
                return ResourceManager.GetString("Modding_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modding process is finished.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Modding_Finished_Caption {
            get {
                return ResourceManager.GetString("Modding_Finished_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified file(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Modified_Files {
            get {
                return ResourceManager.GetString("Modified_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No device connected.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string No_Device_Connected {
            get {
                return ResourceManager.GetString("No_Device_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open workspace과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Open_Workspace {
            get {
                return ResourceManager.GetString("Open_Workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opens workspace directory.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Open_Workspace_Desc {
            get {
                return ResourceManager.GetString("Open_Workspace_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patch Description과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Patch_Desc {
            get {
                return ResourceManager.GetString("Patch_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press Next button to continue.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Press_Next_Button {
            get {
                return ResourceManager.GetString("Press_Next_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prev과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pull과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Pull_Files {
            get {
                return ResourceManager.GetString("Pull_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File pulling completed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Pull_Finished {
            get {
                return ResourceManager.GetString("Pull_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Push과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Push_Files {
            get {
                return ResourceManager.GetString("Push_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File pushing completed. Want to reboot device?
        ///(To prevent black screen, wake device before click yes button.)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Push_Finished {
            get {
                return ResourceManager.GetString("Push_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required file(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Required_Files {
            get {
                return ResourceManager.GetString("Required_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saved!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Script is running...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Script_Begin {
            get {
                return ResourceManager.GetString("Script_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End of script.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Script_End {
            get {
                return ResourceManager.GetString("Script_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There was error(s) while running script.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Script_Has_Problem {
            get {
                return ResourceManager.GetString("Script_Has_Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Select_All {
            get {
                return ResourceManager.GetString("Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Mod과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Select_Mod {
            get {
                return ResourceManager.GetString("Select_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Signing... :{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Signing {
            get {
                return ResourceManager.GetString("Signing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MM! needs software update to: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Version_Required {
            get {
                return ResourceManager.GetString("Version_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save modded Files.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Workspace_Save_Button {
            get {
                return ResourceManager.GetString("Workspace_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save modded files to Workspace directory.
        ///It&apos;s useful for applying multiple mods to same file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Workspace_Save_Desc {
            get {
                return ResourceManager.GetString("Workspace_Save_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save last works to Workspace directory.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Workspace_Save_Previous {
            get {
                return ResourceManager.GetString("Workspace_Save_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create ZIP Package과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZipPackaging_Batch_Button {
            get {
                return ResourceManager.GetString("ZipPackaging_Batch_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create ZIP Package from Workspace folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZipPackaging_Batch_Desc {
            get {
                return ResourceManager.GetString("ZipPackaging_Batch_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create ZIP Package과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZipPackaging_Button {
            get {
                return ResourceManager.GetString("ZipPackaging_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creates recovery-flashable zip package.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZipPackaging_Desc {
            get {
                return ResourceManager.GetString("ZipPackaging_Desc", resourceCulture);
            }
        }
    }
}
